const http = require('http');
const fs = require('fs');
const express = require('express');
const status = require('express-status-monitor');
const zlib = require('zlib')
const app = express();
app.use(status());



//Make a zip file 
// fs.createReadStream('./read/subfolder/write.txt').pipe(zlib.createGzip().pipe(fs.createWriteStream('./read/subfolder/AutoGenerated.zip')));


app.get('/', (req, res)=>{
    const readFileWithStream = fs.createReadStream('./read/subfolder/write.txt', 'utf-8');
    readFileWithStream.on('data', (chunk)=> res.write(chunk));
    readFileWithStream.on('end', ()=> res.end());
})

// Without Stream the data first store in server memory till the file is completely read 
// (issue occures when the file to read is large)
// app.get('/', (req, res) => {
//     const readFileWithoutStream = fs.readFile('./read/subfolder/write.txt', (err, data)=>{
//         res.end(data);
//     });
// })


app.listen(2000, ()=>{
    console.log(`Server is Running at http://localhost:2000`);
})